version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "task-warrior-capstone"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
